#!/bin/bash
# Skript, mis väljastab tärnidest ristküliku, kus esimene ja viimane rida on täidetud ning sisemised read on tühjad keskelt

echo -n "Sisesta ridade arv: "
read rida
echo -n "Sisesta tärnide arv reas: "
read tarnid

echo

for ((i=1; i<=rida; i++)); do
    echo -n "$i. "
    for ((j=1; j<=tarnid; j++)); do
        if [ $i -eq 1 ] || [ $i -eq $rida ] || [ $j -eq 1 ] || [ $j -eq $tarnid ]; then
            echo -n "* "
        else
            echo -n "  "
        fi
    done
    echo
done
