#!/bin/bash
# Skript, mis väljastab kolmnurga, kus ringid muutuvad tärnideks vasakult paremale

echo -n "Sisesta ridade arv: "
read rida

echo

for ((i=1; i<=rida; i++)); do
    echo -n "$i. "
    for ((j=1; j<=rida; j++)); do
        if [ $j -gt $((rida - i)) ]; then
            echo -n "* "
        else
            echo -n "o "
        fi
    done
    echo
done
